### ISSUE TITLE
Fix timezone in clock

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-goals#10]
![image](https://user-images.githubusercontent.com/1935403/134789472-2f3a45e8-b61f-40b6-a17a-68825f9c2158.png)

E.g I am in Pacific time, and I see IST

**Comment by shubham-y** [comment]
I would like to take this issue

**Comment by rajakvk** [comment]
We may use chrome dev tool bar to test the fix. Refer this [article](https://dev.to/aileenr/how-to-spoof-your-timezone-in-google-chrome-48ch) to spoof time zone.
