### ISSUE TITLE
Setup PR template 

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-goals#134]
### template to be used 
```md
### Issue:

### Description:

### Anything you would like to inform the reviewer about:

### Dev Tested:
- [ ] Yes
- [ ] No

### Put the Feature behind Feature Flag
- [ ] Yes
- [ ] No

### Test Stats

### Images/video of the change:

### Follow-up Issues (if any):

> NOTE: After your PR is merged in main please verify its working on prod and raise a dev to main PR

```
For reference on how to do the same, you can check [website-status](https://github.com/Real-Dev-Squad/website-status)

NOTE: If you face any problem please message in  [#🔮goals-site-vue ](https://discord.com/channels/673083527624916993/791420059884060683)

**Comment by suhaasya** [comment]
@bhtibrewal assign it to me. will do it before 27 july.

**Comment by suhaasya** [comment]
@bhtibrewal can you please review the PR.

**Comment by bhtibrewal** [comment]
done
