### ISSUE TITLE
Goal PRD

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-goals#136]
## User Story 

- [ ] As a user, I should be able to view all public goal to keep thing transparent.
- [ ] As a user, I should be able to view all goals assigned to me in a click.
- [ ] As a user, I should be able to create a new goal for myself.
- [ ] As a user, I should be able to edit my goals. 

## Super user

- [ ] As a superuser, I should be able to view all public goals.
- [ ] As a superuser, I should be able to filter/sort based on created at, status, and assigned to better keep track of goals.
- [ ] As a superuser, I should be able to create new goals with just the title of goal to keep things convenient.
- [ ] As a superuser, I should be able to assign people goals.
- [ ] As a superuser, I should be able to update the details of any public goal.

As a superuser, I should be able to create goal templates, to reuse goal details.

## Authentication Flow
- [x] (Django) Goal Authentication middleware
- [ ] (Vue) Frontend authentication sync
- [ ] (Node js) RDS backend sync
![image](https://github.com/Real-Dev-Squad/website-goals/assets/63191499/ebd5e82d-e96c-44c6-8cb9-0af0af576c2c)
## Authorization
- [ ] Authorization middleware

![image](https://github.com/Real-Dev-Squad/website-goals/assets/63191499/90a0c070-d49d-4b31-a5f8-fd95f6371ea5)

**Comment by bhtibrewal** [comment]
### Discussion with Ankush 
- Status of Goal
- 

### Action Items 
- Fix CI/CD
- 

### Additional Features
- set deadlines for 
- status 
- Snooze a goal

**Comment by ivinayakg** [comment]
## Goal Template
- Is a structure/ blueprint which will be used to create a Goal.

### Current Tasks
- Permissions structure to be created for the REST APIs (29th August)
- changes in token_custom to change into the User model (29th August)
- roles to be supported in the user model and the APIs (29th August)
- goals status enum (easy) (Ongoing | Completed) (18th August)
- Pagination, Admin changes, Soft Delete (18th August)
- Priority *** CI/CD setup (testing, staging deployment, prod deployment) (25th August)
