### ISSUE TITLE
footer link correction of goal site 

### ISSUE THREAD

**Issue by Kshashank99** [Real-Dev-Squad/website-goals#22]
1.  When clicked on 'Open source repo' at the footer of https://goals.realdevsquad.com/ it gets redirected to Member site repo instead of goal site vue repo i.e https://github.com/Real-Dev-Squad/website-goals.

![image](https://user-images.githubusercontent.com/64394213/148396079-639cee01-d02f-4e15-a3e8-06105c28c643.png)

2. Remove that code Fragment from the link too.
![image](https://user-images.githubusercontent.com/64394213/148401891-8452c163-b2f1-4a8e-befc-956d257492be.png)

**Comment by palakgupta2712** [comment]
Can I work on this issue?
