### ISSUE TITLE
Add RDS logo and Name in page header.

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-goals#45]
Example -
![image](https://user-images.githubusercontent.com/63191499/180660381-0e14c21c-0389-4e4d-88aa-21ba42062a2c.png)

Required Name -
Goals | Real Dev Squad

**Comment by gurleen3** [comment]
Hey @pallabez! Correct me if am wrong, I believe the code for same is in nuxt.config.js?

**Comment by pallabez** [comment]
Yup. You have to change in nuxt.config.js.

**Comment by RitikJaiswal75** [comment]
Would like to pick it up
