### ISSUE TITLE
Goal Schemas

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-goals#55]
### Goal
`id`; String
`title`: String
`description`: String
`type`: String
`resources`: Array<link>
`createdBy`: Timestamp
`createdAt`: Timestamp
`access`: Array<String>

### UserGoal
`goalId`: String
`userId`: String
`startOn`: timestamp
`endOn`: timestamp
`percentageCompleted`: Integer
`assignedBy`: String
`status`: String
`deferUntil`: timestamp

## Advantage
- Goals should be reusable
- Should be as configurable as possible
- Data should be normalized
- User model shouldn't be affected

**Comment by ivinayakg** [comment]
Why do we need assignee in the `UserGoal` model, 
UserId is already there. Or there is some other purpose served by it ?

**Comment by pallabez** [comment]
> Why do we need assignee in the `UserGoal` model, 
> UserId is already there. Or there is some other purpose served by it ?

Missed that. Thanks

**Comment by pallabez** [comment]
Tracked on - https://github.com/Real-Dev-Squad/website-goals/discussions/65
